SELECT USER_EVT.ID AS ID
FROM (
    SELECT G.ID, SUM( P.ID ) AS FLAG
    FROM GAME_USERS G LEFT JOIN PAYMENTS P ON G.ID = P.USER_ID
    GROUP BY G.ID
    ORDER BY FLAG ASC
) USER_EVT
WHERE USER_EVT.FLAG IS NULL