CREATE TABLE SUBWAY_STATIONS (
  ID INT(5) NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE LINE_ROUTES (
  ID INT(5) NOT NULL,
  LINE_COLOR VARCHAR(20) NOT NULL,
  STATION_ID INT(5) NOT NULL,
  DRIVE_ORDER INT(5) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO SUBWAY_STATIONS VALUE(7, "Barbican");
INSERT INTO SUBWAY_STATIONS VALUE(9, "Station1");
INSERT INTO SUBWAY_STATIONS VALUE(16, "Bethnal Green");
INSERT INTO SUBWAY_STATIONS VALUE(19, "Liverpool Street");
INSERT INTO SUBWAY_STATIONS VALUE(21, "Mile End");

INSERT INTO LINE_ROUTES VALUE(1, "Green", 9, 1);
INSERT INTO LINE_ROUTES VALUE(3, "Red", 16, 2);
INSERT INTO LINE_ROUTES VALUE(12, "Yellow", 19, 2);
INSERT INTO LINE_ROUTES VALUE(17, "Yellow", 7, 1);
INSERT INTO LINE_ROUTES VALUE(20, "Red", 19, 3);
INSERT INTO LINE_ROUTES VALUE(21, "Red", 21, 1);
INSERT INTO LINE_ROUTES VALUE(22, "Green", 16, 2);