SELECT SS.ID, SS.NAME
FROM SUBWAY_STATIONS SS INNER JOIN (
  SELECT LR.STATION_ID
  FROM LINE_ROUTES LR INNER JOIN (
    SELECT MAX(DRIVE_ORDER) AS MAXORD
    FROM (
      SELECT ANY_VALUE(DRIVE_ORDER) AS DRIVE_ORDER
      FROM LINE_ROUTES
      GROUP BY LINE_COLOR
    ) MAX_DRIVE_ORDER
  ) DO ON LR.DRIVE_ORDER = DO.MAXORD
  GROUP BY LR.STATION_ID
) LR_OVER_TWO ON SS.ID = LR_OVER_TWO.STATION_ID
ORDER BY SS.ID ASC